### ISSUE TITLE
Error: Format Items not showing

### ISSUE THREAD

**Issue by Atcross** [anekos/copyf-webextension#3]
Greetings,

Since the last update the program is not displaying all the format options. If any changes are made to the format codes then all items disappear.

This is true in both firefox and chrome.

Great program by the way. I use it a lot. Thanks for your time.
Timothy

**Comment by anekos** [comment]
Thanks.
My copyf shows some the format options, but I could find some missing options.

**Comment by tyru** [comment]
@Atcross could you tell me

* what the format options are missing
* steps to reproduce?

**Comment by anekos** [comment]
copyf will be fixed!

Thank you, @Atcross and @tyru !

**Comment by Atcross** [comment]
Greetings,

At first all items show up, but then if I make any changes then all goes blank.

Or, if I hit the control key then everything returns with the all For Tabs checked. But then if I go to uncheck that all disappears.

Sounds confusing but that is what it is doing. <smile>

Thanks for fixing this!
Timothy
